### ISSUE TITLE
Create Disclaimer page

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/tokenbridge-xapp-gui#32]
continue should go to ReviewPage 
cancel should go back to home

![Screen Shot 2021-08-24 at 3 21 02 PM](https://user-images.githubusercontent.com/3814795/130698245-d52697ae-712b-4a6b-91eb-281bd34a9b0c.png)

Use HeroWithButtons Component

**Comment by aaronmgdr** [comment]
for v1 dont worry about the rainbow text

**Comment by michellewong793** [comment]
ok
